# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf9af65c3526f1fb1e6b9afd2752372168d8fb064ebfc806e58e5fcf43ec0518058291d77c82b0ebd1ac4c71e54061abdeb9f99632a66d315fec001f248544bf
  paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  paypal_secret_id: <%= ENV["PAYPAL_SECRET_ID"] %>

test:
  secret_key_base: 48fd59798281fbfd36bd01bea278724465c293f4096ba25f13be08dcf625c2c7d7380ca348d656dff00f3d70b4fb199bfc860f9b5e8b2d4474126763f86bfd7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  paypal_secret_id: <%= ENV["PAYPAL_SECRET_ID"] %>
